/******************************************************************************
 * @file storage_assets.c
 *
 * @par dependencies
 * - service_storage_facade.h
 * - cfg_storage.h
 * - lvgl.h
 *
 * @author Ethan-Hang
 *
 * @brief LVGL pointer-sprite assets that live on the external W25Q64 flash.
 *
 *        At first boot, the LVGL sub-region is unprovisioned (0xFF).  This
 *        translation unit:
 *
 *          1. Holds a RAM mirror buffer for each pointer image.
 *          2. Exports a parallel set of `lv_img_dsc_t` descriptors
 *             (`*_ext`) whose `.data` points at those RAM buffers.
 *          3. Implements storage_assets_bootstrap() which reads the magic,
 *             writes the original .rodata image data into the external
 *             flash on a magic mismatch, and finally re-reads the three
 *             sprites back into the RAM mirrors.
 *
 *        setup_scr_screen.c references the `*_ext` descriptors so the
 *        analog clock needles draw from the RAM mirror that is fed by the
 *        external flash.  The original `_fen_alpha_70x5_map` etc. arrays
 *        remain in .rodata only so we can self-bootstrap a freshly-erased
 *        chip without an external programming step.
 *
 * @version V1.0 2026-05-08
 *
 * @note 1 tab == 4 spaces!
 *
 *****************************************************************************/

//******************************** Includes *********************************//
#include "service_storage_facade.h"
#include "cfg_storage.h"
#include "lv_port_extflash.h"

#include "lvgl.h"
#include "Debug.h"

#include <stdint.h>
#include <string.h>
//******************************** Includes *********************************//

//******************************** Defines **********************************//

//******************************** Defines **********************************//

//******************************* Variables *********************************//
/* Original .rodata maps generated by gui_guider, kept only to seed the
 * external flash on first boot. */
extern const uint8_t _fen_alpha_70x5_map[];
extern const uint8_t _miao_alpha_70x5_map[];
extern const uint8_t _time_alpha_40x5_map[];

/* RAM mirrors filled by Read_LvglData() during bootstrap. */
static uint8_t s_au8_fen_ram [CFG_LVGL_ASSET_FEN_SIZE];
static uint8_t s_au8_miao_ram[CFG_LVGL_ASSET_MIAO_SIZE];
static uint8_t s_au8_time_ram[CFG_LVGL_ASSET_TIME_SIZE];

/**
 * Externally-visible LVGL descriptors that point at the RAM mirrors.
 * Exposed via gui_guider.h's LV_IMG_DECLARE so setup_scr_screen.c can
 * reference them without including this translation unit's header.
 */
const lv_img_dsc_t _fen_alpha_70x5_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = 70,
    .header.h           = 5,
    .data_size          = CFG_LVGL_ASSET_FEN_SIZE,
    .data               = s_au8_fen_ram,
};

const lv_img_dsc_t _miao_alpha_70x5_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = 70,
    .header.h           = 5,
    .data_size          = CFG_LVGL_ASSET_MIAO_SIZE,
    .data               = s_au8_miao_ram,
};

const lv_img_dsc_t _time_alpha_40x5_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = 40,
    .header.h           = 5,
    .data_size          = CFG_LVGL_ASSET_TIME_SIZE,
    .data               = s_au8_time_ram,
};

/* 240x240 alpha background — too large for a RAM mirror, served line by
 * line directly off W25Q64 by the lv_port_extflash decoder.  The `.data`
 * pointer is repurposed: it carries the metadata struct the decoder
 * inspects (offset, geometry, pixel size).  data_size = 0 tells LVGL it
 * cannot copy the buffer wholesale and must call read_line_cb. */
static const lv_extflash_meta_t s_biaopan1_meta = {
    .magic      = LV_EXTFLASH_DECODER_MAGIC,
    .ext_offset = CFG_LVGL_ASSET_BIAOPAN1_OFFSET,
    .width      = CFG_LVGL_ASSET_BIAOPAN1_W,
    .height     = CFG_LVGL_ASSET_BIAOPAN1_H,
    .px_size    = CFG_LVGL_ASSET_BIAOPAN1_PX_SIZE,
};

const lv_img_dsc_t _biaopan1_alpha_240x240_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_BIAOPAN1_W,
    .header.h           = CFG_LVGL_ASSET_BIAOPAN1_H,
    .data_size          = 0,
    .data               = (const uint8_t *)&s_biaopan1_meta,
};
//******************************* Variables *********************************//

//******************************* Functions *********************************//
/**
 * @brief Sequentially read the three pointer sprites from external flash
 *        into their RAM mirrors.
 */
static ext_flash_status_t lvgl_assets_load_to_ram(void)
{
    ext_flash_status_t st;

    st = Read_LvglData(CFG_LVGL_ASSET_FEN_OFFSET,
                       CFG_LVGL_ASSET_FEN_SIZE,
                       s_au8_fen_ram);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "load fen failed st=%d", (int)st);
        return st;
    }

    st = Read_LvglData(CFG_LVGL_ASSET_MIAO_OFFSET,
                       CFG_LVGL_ASSET_MIAO_SIZE,
                       s_au8_miao_ram);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "load miao failed st=%d", (int)st);
        return st;
    }

    st = Read_LvglData(CFG_LVGL_ASSET_TIME_OFFSET,
                       CFG_LVGL_ASSET_TIME_SIZE,
                       s_au8_time_ram);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "load time failed st=%d", (int)st);
        return st;
    }

    return EXT_FLASH_OK;
}

/**
 * @brief Write the .rodata seed images + magic into the LVGL sub-region.
 *        The magic is written LAST so a power loss midway through means
 *        the next boot retries the bootstrap.
 */
static ext_flash_status_t lvgl_assets_provision(void)
{
    ext_flash_status_t st;

    st = Write_LvglData(CFG_LVGL_ASSET_FEN_OFFSET,
                        CFG_LVGL_ASSET_FEN_SIZE,
                        _fen_alpha_70x5_map);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write fen failed st=%d", (int)st);
        return st;
    }

    st = Write_LvglData(CFG_LVGL_ASSET_MIAO_OFFSET,
                        CFG_LVGL_ASSET_MIAO_SIZE,
                        _miao_alpha_70x5_map);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write miao failed st=%d", (int)st);
        return st;
    }

    st = Write_LvglData(CFG_LVGL_ASSET_TIME_OFFSET,
                        CFG_LVGL_ASSET_TIME_SIZE,
                        _time_alpha_40x5_map);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write time failed st=%d", (int)st);
        return st;
    }

    /* Magic is written last so a partial bootstrap retries cleanly. */
    const uint32_t magic_val = CFG_LVGL_ASSET_MAGIC;
    st = Write_LvglData(CFG_LVGL_ASSET_MAGIC_OFFSET,
                        CFG_LVGL_ASSET_MAGIC_SIZE,
                        (const uint8_t *)&magic_val);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write magic failed st=%d", (int)st);
        return st;
    }

    return EXT_FLASH_OK;
}

ext_flash_status_t storage_assets_bootstrap(void)
{
    uint32_t            magic = 0U;
    ext_flash_status_t  st;

    DEBUG_OUT(i, W25Q64_LOG_TAG, "assets bootstrap: probing magic");

    st = Read_LvglData(CFG_LVGL_ASSET_MAGIC_OFFSET,
                       CFG_LVGL_ASSET_MAGIC_SIZE,
                       (uint8_t *)&magic);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG,
                  "assets bootstrap: read magic failed st=%d", (int)st);
        return st;
    }

    if (CFG_LVGL_ASSET_MAGIC == magic)
    {
        DEBUG_OUT(i, W25Q64_LOG_TAG,
                  "assets bootstrap: magic ok (0x%08X), skipping write",
                  (unsigned int)magic);
    }
    else
    {
        DEBUG_OUT(i, W25Q64_LOG_TAG,
                  "assets bootstrap: magic mismatch (0x%08X), writing",
                  (unsigned int)magic);
        st = lvgl_assets_provision();
        if (EXT_FLASH_OK != st)
        {
            return st;
        }
        DEBUG_OUT(i, W25Q64_LOG_TAG, "assets bootstrap: write done");
    }

    st = lvgl_assets_load_to_ram();
    if (EXT_FLASH_OK != st)
    {
        return st;
    }

    DEBUG_OUT(i, W25Q64_LOG_TAG, "assets bootstrap: ram mirrors filled");
    return EXT_FLASH_OK;
}
//******************************* Functions *********************************//
