/******************************************************************************
 * @file storage_assets.c
 *
 * @par dependencies
 * - service_storage_facade.h
 * - cfg_storage.h
 * - lvgl.h
 *
 * @author Ethan-Hang
 *
 * @brief LVGL assets that live on the external W25Q64 flash.
 *
 *        Two classes of asset:
 *
 *          1. Pointer sprites (fen 80x8, miao 70x5, time 50x8).
 *             Small enough to mirror into MCU RAM at boot.  Firmware
 *             carries a copy in .rodata so a virgin W25Q64 can be
 *             self-provisioned, then the mirror is filled by reading
 *             back from the external flash.  setup_scr_Clock_*.c
 *             references the `*_ext` lv_img_dsc_t descriptors here.
 *
 *          2. Large backgrounds (MDLBG 240x280, biaopan1 200x200).
 *             Too large for RAM (200+ KB) and intentionally kept out of
 *             firmware .rodata.  Served line-by-line straight off W25Q64
 *             by the lv_port_extflash decoder.  The lv_img_dsc_t .data
 *             pointer is overloaded to carry an lv_extflash_meta_t the
 *             decoder recognises by its magic field.  data_size = 0
 *             tells LVGL it must call read_line_cb.
 *
 *        First-boot provisioning ONLY covers the sprites.  The two
 *        backgrounds must be written by `make flash-assets` before they
 *        will render -- absent that, the analog clock paints over the
 *        default background (no streaming source available).
 *
 * @version V1.1 2026-05-24  Switch to new SquareLine watch UI assets.
 *
 * @note 1 tab == 4 spaces!
 *
 *****************************************************************************/

//******************************** Includes *********************************//
#include "service_storage_facade.h"
#include "cfg_storage.h"
#include "lv_port_extflash.h"

#include "lvgl.h"
#include "Debug.h"

#include <stdint.h>
#include <string.h>
//******************************** Includes *********************************//

//******************************* Variables *********************************//
/* Original .rodata maps generated by gui_guider, kept only to seed the
 * external flash on first boot. */
extern const uint8_t _fen_alpha_80x8_map[];
extern const uint8_t _miao_alpha_70x5_map[];
extern const uint8_t _time_alpha_50x8_map[];

/* RAM mirrors filled by Read_LvglData() during bootstrap. */
static uint8_t s_au8_fen_ram [CFG_LVGL_ASSET_FEN_SIZE];
static uint8_t s_au8_miao_ram[CFG_LVGL_ASSET_MIAO_SIZE];
static uint8_t s_au8_time_ram[CFG_LVGL_ASSET_TIME_SIZE];

/**
 * Externally-visible LVGL descriptors that point at the RAM mirrors.
 * Exposed via gui_guider.h's LV_IMG_DECLARE so setup_scr_Clock_*.c can
 * reference them without including this translation unit's header.
 */
const lv_img_dsc_t _fen_alpha_80x8_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_FEN_W,
    .header.h           = CFG_LVGL_ASSET_FEN_H,
    .data_size          = CFG_LVGL_ASSET_FEN_SIZE,
    .data               = s_au8_fen_ram,
};

const lv_img_dsc_t _miao_alpha_70x5_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_MIAO_W,
    .header.h           = CFG_LVGL_ASSET_MIAO_H,
    .data_size          = CFG_LVGL_ASSET_MIAO_SIZE,
    .data               = s_au8_miao_ram,
};

const lv_img_dsc_t _time_alpha_50x8_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_TIME_W,
    .header.h           = CFG_LVGL_ASSET_TIME_H,
    .data_size          = CFG_LVGL_ASSET_TIME_SIZE,
    .data               = s_au8_time_ram,
};

/* MDLBG 240x280 alpha background — too large for a RAM mirror, served
 * line by line directly off W25Q64 by the lv_port_extflash decoder. */
static const lv_extflash_meta_t s_mdlbg_meta = {
    .magic      = LV_EXTFLASH_DECODER_MAGIC,
    .ext_offset = CFG_LVGL_ASSET_MDLBG_OFFSET,
    .width      = CFG_LVGL_ASSET_MDLBG_W,
    .height     = CFG_LVGL_ASSET_MDLBG_H,
    .px_size    = CFG_LVGL_ASSET_MDLBG_PX_SIZE,
};

const lv_img_dsc_t _MDLBG_alpha_240x280_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_MDLBG_W,
    .header.h           = CFG_LVGL_ASSET_MDLBG_H,
    .data_size          = 0,
    .data               = (const uint8_t *)&s_mdlbg_meta,
};

/* biaopan1 200x200 alpha background — same streaming pattern. */
static const lv_extflash_meta_t s_biaopan1_meta = {
    .magic      = LV_EXTFLASH_DECODER_MAGIC,
    .ext_offset = CFG_LVGL_ASSET_BIAOPAN1_OFFSET,
    .width      = CFG_LVGL_ASSET_BIAOPAN1_W,
    .height     = CFG_LVGL_ASSET_BIAOPAN1_H,
    .px_size    = CFG_LVGL_ASSET_BIAOPAN1_PX_SIZE,
};

const lv_img_dsc_t _biaopan1_200x200_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_BIAOPAN1_W,
    .header.h           = CFG_LVGL_ASSET_BIAOPAN1_H,
    .data_size          = 0,
    .data               = (const uint8_t *)&s_biaopan1_meta,
};

/* watchdight 1/2/3 walking-step icon frames (60x60 alpha each).  Streamed
 * line-by-line from W25Q64 -- each frame is 10800 B; embedding all three
 * in .rodata would cost 32 KB Flash for icons that are otherwise static.
 * Same lv_extflash_meta_t protocol as the larger backgrounds. */
static const lv_extflash_meta_t s_watchdight1_meta = {
    .magic      = LV_EXTFLASH_DECODER_MAGIC,
    .ext_offset = CFG_LVGL_ASSET_WATCHDIGHT1_OFFSET,
    .width      = CFG_LVGL_ASSET_WATCHDIGHT1_W,
    .height     = CFG_LVGL_ASSET_WATCHDIGHT1_H,
    .px_size    = CFG_LVGL_ASSET_WATCHDIGHT1_PX_SIZE,
};

const lv_img_dsc_t _watchdight1_alpha_60x60_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_WATCHDIGHT1_W,
    .header.h           = CFG_LVGL_ASSET_WATCHDIGHT1_H,
    .data_size          = 0,
    .data               = (const uint8_t *)&s_watchdight1_meta,
};

static const lv_extflash_meta_t s_watchdight2_meta = {
    .magic      = LV_EXTFLASH_DECODER_MAGIC,
    .ext_offset = CFG_LVGL_ASSET_WATCHDIGHT2_OFFSET,
    .width      = CFG_LVGL_ASSET_WATCHDIGHT2_W,
    .height     = CFG_LVGL_ASSET_WATCHDIGHT2_H,
    .px_size    = CFG_LVGL_ASSET_WATCHDIGHT2_PX_SIZE,
};

const lv_img_dsc_t _watchdight2_alpha_60x60_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_WATCHDIGHT2_W,
    .header.h           = CFG_LVGL_ASSET_WATCHDIGHT2_H,
    .data_size          = 0,
    .data               = (const uint8_t *)&s_watchdight2_meta,
};

static const lv_extflash_meta_t s_watchdight3_meta = {
    .magic      = LV_EXTFLASH_DECODER_MAGIC,
    .ext_offset = CFG_LVGL_ASSET_WATCHDIGHT3_OFFSET,
    .width      = CFG_LVGL_ASSET_WATCHDIGHT3_W,
    .height     = CFG_LVGL_ASSET_WATCHDIGHT3_H,
    .px_size    = CFG_LVGL_ASSET_WATCHDIGHT3_PX_SIZE,
};

const lv_img_dsc_t _watchdight3_alpha_60x60_ext = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = CFG_LVGL_ASSET_WATCHDIGHT3_W,
    .header.h           = CFG_LVGL_ASSET_WATCHDIGHT3_H,
    .data_size          = 0,
    .data               = (const uint8_t *)&s_watchdight3_meta,
};
//******************************* Variables *********************************//

//******************************* Functions *********************************//
/**
 * @brief Sequentially read the three pointer sprites from external flash
 *        into their RAM mirrors.
 */
static ext_flash_status_t lvgl_assets_load_to_ram(void)
{
    ext_flash_status_t st;

    st = Read_LvglData(CFG_LVGL_ASSET_FEN_OFFSET,
                       CFG_LVGL_ASSET_FEN_SIZE,
                       s_au8_fen_ram);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "load fen failed st=%d", (int)st);
        return st;
    }

    st = Read_LvglData(CFG_LVGL_ASSET_MIAO_OFFSET,
                       CFG_LVGL_ASSET_MIAO_SIZE,
                       s_au8_miao_ram);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "load miao failed st=%d", (int)st);
        return st;
    }

    st = Read_LvglData(CFG_LVGL_ASSET_TIME_OFFSET,
                       CFG_LVGL_ASSET_TIME_SIZE,
                       s_au8_time_ram);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "load time failed st=%d", (int)st);
        return st;
    }

    return EXT_FLASH_OK;
}

/**
 * @brief Write the .rodata seed images + magic into the LVGL sub-region.
 *        The magic is written LAST so a power loss midway through means
 *        the next boot retries the bootstrap.
 */
static ext_flash_status_t lvgl_assets_provision(void)
{
    ext_flash_status_t st;

    st = Write_LvglData(CFG_LVGL_ASSET_FEN_OFFSET,
                        CFG_LVGL_ASSET_FEN_SIZE,
                        _fen_alpha_80x8_map);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write fen failed st=%d", (int)st);
        return st;
    }

    st = Write_LvglData(CFG_LVGL_ASSET_MIAO_OFFSET,
                        CFG_LVGL_ASSET_MIAO_SIZE,
                        _miao_alpha_70x5_map);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write miao failed st=%d", (int)st);
        return st;
    }

    st = Write_LvglData(CFG_LVGL_ASSET_TIME_OFFSET,
                        CFG_LVGL_ASSET_TIME_SIZE,
                        _time_alpha_50x8_map);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write time failed st=%d", (int)st);
        return st;
    }

    /* Magic is written last so a partial bootstrap retries cleanly. */
    const uint32_t magic_val = CFG_LVGL_ASSET_MAGIC;
    st = Write_LvglData(CFG_LVGL_ASSET_MAGIC_OFFSET,
                        CFG_LVGL_ASSET_MAGIC_SIZE,
                        (const uint8_t *)&magic_val);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG, "write magic failed st=%d", (int)st);
        return st;
    }

    return EXT_FLASH_OK;
}

ext_flash_status_t storage_assets_bootstrap(void)
{
    uint32_t            magic = 0U;
    ext_flash_status_t  st;

    DEBUG_OUT(i, W25Q64_LOG_TAG, "assets bootstrap: probing magic");

    st = Read_LvglData(CFG_LVGL_ASSET_MAGIC_OFFSET,
                       CFG_LVGL_ASSET_MAGIC_SIZE,
                       (uint8_t *)&magic);
    if (EXT_FLASH_OK != st)
    {
        DEBUG_OUT(e, W25Q64_ERR_LOG_TAG,
                  "assets bootstrap: read magic failed st=%d", (int)st);
        return st;
    }

    if (CFG_LVGL_ASSET_MAGIC == magic)
    {
        DEBUG_OUT(i, W25Q64_LOG_TAG,
                  "assets bootstrap: magic ok (0x%08X), skipping write",
                  (unsigned int)magic);
    }
    else
    {
        DEBUG_OUT(i, W25Q64_LOG_TAG,
                  "assets bootstrap: magic mismatch (0x%08X), writing",
                  (unsigned int)magic);
        st = lvgl_assets_provision();
        if (EXT_FLASH_OK != st)
        {
            return st;
        }
        DEBUG_OUT(i, W25Q64_LOG_TAG, "assets bootstrap: write done");
    }

    st = lvgl_assets_load_to_ram();
    if (EXT_FLASH_OK != st)
    {
        return st;
    }

    DEBUG_OUT(i, W25Q64_LOG_TAG, "assets bootstrap: ram mirrors filled");
    return EXT_FLASH_OK;
}
//******************************* Functions *********************************//
